# EVENTS
from pygame.locals import (USEREVENT)

ALIEN_EVENT = 1
ADD_ALIEN = USEREVENT + ALIEN_EVENT
ALIEN_TIME = 2000

BULLET_EVENT = 2

ASTEROID_EVENT = 3
ADD_ASTEROID = USEREVENT + ASTEROID_EVENT
ASTEROID_TIME = 1000

DEATH_EVENT = 4

